* ST 0.8.5
This is my patched build for Suckless' terminal [[https://st.suckless.org/][st]]. All applied patches can be found in the =patches= directory.

* Patches
This build has been patched with:
- =Anysize= --- fix sizing issues for tilling window managers.
- =Externalpipe= --- reading and writing st's screen through a pipe.
- =Externalpipe-eternal= --- use externalpipe onto the entire terminal history (requires scrollback patch).
- =Scrollback= --- Scroll back through terminal output.

* Installation
To install this build of =st= first clone this repo:
#+BEGIN_SRC 
$ git clone https://github.com/BryanRi/st.git
#+END_SRC
Then go into the =st= directory and install it:
#+BEGIN_SRC 
$ cd st
$ sudo make clean install
#+END_SRC

* Key bindings
Some useful keybindings:
- =C-S-n=, =C-S-e= --- zoom in/out
- =C-n=, =C-e= --- scroll up/down one line
- =M-n=, =M-e= --- scroll up/down one page
- =C-S-c=, =C-S-v= --- copy/paste
- =M-l=, =M-y= --- open/copy urls visible in the terminal (chosen with dmenu)(*)
- =M-o= --- copy output from a command to the clipboard (command is chosen with dmenu)(*)
  
(*) Require the scripts =st-copyout= and =st-urlhandler= to be in the PATH.

* Todo
Add the following patches:
- =csi_22_23=
- =keyboard-select=
- =universal-scroll=
- =selectioncolors=
